config/routes.rb
Rails.application.routes.draw do

  mount GogglesCore::Engine => "home/index"

  devise_for :admins

  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'

  root to: "data_import/home#step1_status", locale: /en|it/

  scope "/" do
    scope "(:locale)", locale: /it|en/ do
      get   "maintenance/index", as: :maintenance

      get  "maintenance/db_structure"
      post "maintenance/db_reset"
      post "maintenance/run_db_migrations"
      post "maintenance/run_sql_exec"

      get  "maintenance/select_meeting"
      post "maintenance/delete_meeting"
      get  "maintenance/select_teams"

      match "maintenance/run_rake",         to: "maintenance#run_rake",  via: [:get, :post]
      match "maintenance/run_bundle",       to: "maintenance#run_bundle",  via: [:get, :post]
      match "maintenance/run_sudo_command", to: "maintenance#run_sudo_command",  via: [:get, :post]
      match "maintenance/restart_apache",   to: "maintenance#restart_apache",  via: [:get, :post]
      match "maintenance/run_src_upgrade",  to: "maintenance#run_src_upgrade",  via: [:get, :post]
      match "maintenance/upload_db_dump",   to: "maintenance#upload_db_dump",  via: [:get, :post]
      match "maintenance/upload_db_seed",   to: "maintenance#upload_db_seed",  via: [:get, :post]

      get "maintenance/download_db_dump"
      get "maintenance/download_team_dump"
      get "maintenance/download_swimmer_dump"
      get "maintenance/download_user_dump"
      get "maintenance/cleanup_output_dir"

      get  "data_import/home/step1_status",                     as: :di_step1_status
      get  "data_import/home/step1_1_team_analysis",            as: :di_step1_1_team_analysis
      post "data_import/home/step1_1_team_analysis_commit",     as: :di_step1_1_team_analysis_commit
      get  "data_import/home/step1_1_swimmer_analysis",         as: :di_step1_1_swimmer_analysis
      post "data_import/home/step1_1_swimmer_analysis_commit",  as: :di_step1_1_swimmer_analysis_commit
      post "data_import/home/step2_checkout",                   as: :di_step2_checkout
      get  "data_import/home/step2_checkout",                   as: :di_step2_checkout_get
      post "data_import/home/step3_commit",                     as: :di_step3_commit
      post "data_import/home/kill_import_session",              as: :di_kill_import_session

      get  "data_import/home/result/:id",   to: "data_import/home#result", as: "di_result"
    end
  end

  get 'json_search/swimmers', format: "json"
  get 'json_search/teams',    format: "json"
  get 'json_search/meetings', format: "json"
  get 'json_search/pools',    format: "json"
end

app/controllers/admin/v2/data_import_controller.rb
# encoding: utf-8
require 'fileutils'                                 # Used to process filenames
require 'common/format'
require_relative '../../../data_import/v2/strategies/data_importer'
require_relative '../../../data_import/v2/strategies/csi_result_parser'
require_relative '../../../data_import/v2/strategies/team_analysis_result_processor'
require_relative '../../../data_import/v2/strategies/swimmer_analysis_result_processor'


=begin

= AdminImportController

  - version:  4.00.741
  - author:   Steve A.

=end
class Admin::V2::DataImportController < ApplicationController

  layout 'admin_v2_data_import'

  # Require authorization before invoking any of this controller's actions:
  before_action :authenticate_admin!
  #-- -------------------------------------------------------------------------
  #++


  # Destroys an existing Data-import session
  #
  def kill_import_session
    data_import_session = DataImportSession.find_by_id( params[:id].to_i )
    if data_import_session
      DataImporter.new( logger, flash, data_import_session ).destroy_data_import_session
    end
    redirect_to( admin_v2_di_step1_status_path() )
  end
  #-- -------------------------------------------------------------------------
  #++


  # Data Import Wizard: START / STATUS
  # Phase #1: upload text file / Select an existing Data-import session
  #
  def step1_status                                   # Retrieve current sessions for the current user and list them:
# DEBUG
#    logger.debug "\r\n\r\n!! ------ admin_import::step1_status -----"
#    logger.debug "current_admin: #{current_admin.inspect}"
    @existing_import_sessions = DataImportSession.where( user_id: current_admin.id )
  end
  #-- -------------------------------------------------------------------------
  #++


  # Data Import Wizard: Phase-1.1 - Team Names Analysis, called only when some problematic
  # team names are found dubious or mis-matched.
  #
  def step1_1_team_analysis
# DEBUG
#    logger.debug "\r\n\r\n!! ------ admin_import::step1_1_team_analysis -----"
#    logger.debug "PARAMS: #{params.inspect}"
                                                    # Propagate forward (phase-3) the parameters from Phase-1, if any:
    @force_missing_meeting_creation = (params[:force_meeting_creation] == 'true') ||
                                      (params[:force_meeting_creation].to_i > 0)
    @force_team_or_swimmer_creation = (params[:force_team_or_swimmer_creation] == 'true') ||
                                      (params[:force_team_or_swimmer_creation].to_i > 0)
    if ( params[:id].to_i > 0 )
      @data_import_session = DataImportSession.find_by_id( params[:id].to_i )
      @analysis_results = DataImportTeamAnalysisResult.where( data_import_session_id: @data_import_session.id )
    else
      @data_import_session = nil
      @analysis_results = []
    end
  end


  # Data Import Wizard: Parallel Phase-1.1 Team-Analysis Commit Phase.
  # (Invoked after the alternative phase-2 outcome, #step1_1_team_analysis, when
  # the Team-Analysis phase has been triggered.)
  # This action has no associated view.
  #
  def step1_1_team_analysis_commit
# DEBUG
    logger.debug "\r\n\r\n!! ------ admin_import::step1_1_team_analysis_commit -----"
    logger.debug "PARAMS: #{params.inspect}"
    overridden_alias_actions = {}
    confirmed_actions_ids    = []
    data_import_session_id   = 0
    must_go_back_on_commit   = false
    is_ok = true
                                                    # Parse parameters:
    params.each do |key, value|
      data_import_session_id = value.to_i if ( key.to_sym == :data_import_session_id)
      if ( key.to_s =~ /id_/i )
        confirmed_actions_ids << ( key.to_s.split('id_')[1] ).to_i
      end
      must_go_back_on_commit = value.to_i > 0 if ( key.to_sym == :must_go_back)
    end
    force_missing_meeting_creation = (params[:force_meeting_creation] == 'true') ||
                                     (params[:force_meeting_creation].to_i > 0)
    force_team_or_swimmer_creation = (params[:force_team_or_swimmer_creation] == 'true') ||
                                     (params[:force_team_or_swimmer_creation].to_i > 0)

    # [Steve] The following override hash has the structure:
    #
    # params[:alias_ids] => {
    #   analysis_result.id.to_s => overridden_alias_team_id.to_s,
    #   #...
    # }
    overridden_alias_actions = params['alias_ids'] if params['alias_ids'].instance_of?( ActiveSupport::HashWithIndifferentAccess )
# DEBUG
#    logger.debug "\r\ndata_import_session_id: #{data_import_session_id}"
#    logger.debug "Confirmed IDs: #{confirmed_actions_ids.inspect}"
#    logger.debug "Overridden Alias IDs: #{overridden_alias_actions.inspect}\r\n- params['alias_ids']: #{params['alias_ids'].class.name}\r\n- params['alias_ids']: #{params['alias_ids'].inspect}"
    data_import_session = DataImportSession.find( data_import_session_id )
    importer            = DataImporter.new( logger, flash, data_import_session )
    result_processor    = V2::TeamAnalysisResultProcessor.new( logger, flash )
                                                    # retrieve results from dedicated table:
    all_results = DataImportTeamAnalysisResult.where( data_import_session_id: data_import_session_id )

    # For each confirmed result, execute the suggested actions (either the team
    # alias is confirmed, or a new Team w/ affiliation must be created from scratch):
    all_results.each do |analysis_result|
      is_confirmed = confirmed_actions_ids.include?( analysis_result.id )
      alias_override_id = overridden_alias_actions.has_key?( analysis_result.id.to_s ) ?
                          overridden_alias_actions[ analysis_result.id.to_s ].to_i :
                          nil
                                                    # Execute the suggested actions:
      is_ok = result_processor.run(
        analysis_result,
        is_confirmed,
        alias_override_id
      )
    end

    importer.set_analysis_logs(
      result_processor.process_log,
      result_processor.sql_executable_log
    )
                                                    # Write the log files anyway:
    importer.write_analysis_logfile( is_ok )
    importer.write_sql_diff_logfile
# DEBUG
#    logger.debug("\r\n- is_ok: #{is_ok}, data_import_session_id: #{data_import_session_id}")
                                                    # Redirect to next action accordingly:
    if is_ok
      flash[:info] = I18n.t('admin_import.team_analysis_completed')
      if must_go_back_on_commit                     # Since we are aborting full-data import, we need to clean up the broken session:
        importer.destroy_data_import_session
      else                                          # Clear just the results from the session if everything is ok:
        # The Log has become too long & complex to be saved into the table!

        # [Steve, 20141111] We cannot save the log on table: the UPDATE statement will take
        # a progressively longer time to complete, slowing the process considerably
        # and eventually make the statement execution fail with MySQL disconnection error.
        # A more quick, professional and permanent solution to obtain the logging serialized
        # on DB it would be to add a separate table entity with a row for each single log
        # event.
        # As it is, the only viable solution is to keep the logging only on file.

        # Quick hack: disregard any update to the log members and keep them just
        # as variables:
#        data_import_session.phase_1_log_will_change!
        data_import_session.phase_1_log << result_processor.process_log
#        data_import_session.sql_diff_will_change!
        data_import_session.sql_diff    << result_processor.sql_executable_log
        data_import_session.phase = 11              # Update "last completed phase" indicator in session (11 = 1.1)
        data_import_session.save!
        DataImportTeamAnalysisResult.where( data_import_session_id: data_import_session_id ).delete_all
                                                    # Go directly to Swimmer name analysis results, if possible:
        if data_import_session.data_import_swimmer_analysis_results.any?
          flash[:info] = I18n.t( 'admin_import.swimmer_analysis_needed' )
          redirect_to(
              admin_v2_di_step1_1_swimmer_analysis_path(
                  id: importer.data_import_session.id,
                  force_meeting_creation: force_missing_meeting_creation ? '1' : nil
              )
          ) and return
        else
          redirect_to(
            admin_v2_di_step2_checkout_path(
              id: data_import_session_id,
              force_meeting_creation: force_missing_meeting_creation ? '1' : '0',
              force_team_or_swimmer_creation: '1' # After the Team analysis, we can serialize the missing teams (WAS: force_team_or_swimmer_creation     ? '1' : '0' )
            )
          ) and return
        end
      end
    else
      redirect_to( admin_v2_di_step1_status_path() ) and return
    end
  end
  #-- -------------------------------------------------------------------------
  #++


  # Data Import Wizard: Phase-1.1 - Swimmer Names Analysis, called only when some problematic
  # swimmer names are found dubious or mis-matched.
  #
  def step1_1_swimmer_analysis
# DEBUG
#    logger.debug "\r\n\r\n!! ------ admin_import::step1_1_swimmer_analysis -----"
#    logger.debug "PARAMS: #{params.inspect}"
                                                    # Propagate forward (phase-3) the parameters from Phase-1, if any:
    @force_missing_meeting_creation = (params[:force_meeting_creation] == 'true') ||
                                      (params[:force_meeting_creation].to_i > 0)
    @force_team_or_swimmer_creation = (params[:force_team_or_swimmer_creation] == 'true') ||
                                      (params[:force_team_or_swimmer_creation].to_i > 0)
    if ( params[:id].to_i > 0 )

app/views/data_import/home/_main_menu.html.haml
.navmenu.navmenu-default.navmenu-fixed-left
  %a.navmenu-brand{ href: root_path }
    = t('admin_import.admin')
    = image_tag( GogglesCore::AppConstants::WEB_APP_LOGO, style: "width: 100px;" )
  = render_navigation( context: 'admin_v2_data_import', level: 1..2, expand_all: true, renderer: :bootstrap )

app/views/data_import/home/_pb_scanned_status.html.haml
= check_box_tag( :pb_scanned, '1', meeting.is_pb_scanned, disabled: true )
= "Personal-best scanned? "
- unless meeting.is_pb_scanned?
  &nbsp;
  - command_line = "zeus rake db:scan_meeting_for_personal_bests persist=true meeting=#{ meeting.id }\r\nzeus rake db:scan_team_records meeting_id=#{ meeting.id }"
  %span{id: "meetingPBScan#{ meeting.id }" }
    .btn.btn-default.btn-xs
      = I18n.t("admin_import.command_to_be_executed")

:javascript
  var popContent = "#{ escape_javascript( text_area_tag(:post_contents, command_line, rows: 6, cols: 80, class: 'col-xs-12 well') ) }";
  $( "#meetingPBScan#{ meeting.id }" ).popover({
    title: "#{ escape_javascript( I18n.t("admin_import.go_to_console_title") ) }",
    html: true,
    content: popContent,
    placement: "bottom"
  });

app/views/data_import/home/_social_fb_post_status.html.haml
= check_box_tag( :fb_posted, '1', meeting.is_fb_posted, disabled: true )
= "FB-posted? "
- unless meeting.is_fb_posted?
  &nbsp;
  - text_key    = is_a_start_list ? "social_post.fb.published_startlist" : "social_post.fb.published_results"
  - action_name = is_a_start_list ? "show_start_list" : "show_full"
  - post_contents = I18n.t( text_key,                                               |
      federation: meeting.season_type.federation_type.short_name,                   |
      year: meeting.header_date.year, meeting: meeting.get_full_name,               |
      city: meeting.swimming_pools.first.city.get_full_name,                        |
      url: "http://master-goggles.org/it/meeting/#{ action_name }/#{ meeting.id }"  |
    ) +                                                                             |
    "\r\n\r\n- #{ I18n.t('admin_import.teams') }: #{ meeting.teams.distinct.unscope(:order).count } / " + |
    "#{ I18n.t('admin_import.swimmers') }: #{ meeting.swimmers.distinct.unscope(:order).count }\r\n" +    |
    "- #{ I18n.t('admin_import.mirs') }: #{ meeting.meeting_individual_results.distinct.unscope(:order).count } / " + |
    "#{ I18n.t('admin_import.mrrs') }: #{ meeting.meeting_relay_results.distinct.unscope(:order).count }\r\n" |
  %span{id: "meetingFB#{ meeting.id }" }
    .btn.btn-default.btn-xs
      = I18n.t("social_post.suggested_title")

:javascript
  var popContent = "#{ escape_javascript( text_area_tag(:post_contents, post_contents, rows: 10, cols: 120, class: 'col-xs-12 well') ) }";
  $( "#meetingFB#{ meeting.id }" ).popover({
    title: "#{ escape_javascript( I18n.t("social_post.total_size", len: post_contents.size) ) }",
    html: true,
    content: popContent,
    placement: "bottom"
  });

app/views/data_import/home/_step2_badges_show.html.haml
- if @badges.count > 0
  %h4
    = I18n.t('admin_import.primary_already_existing')
    = " (tot. #{ @badges.count })"
  %table.table.table-striped.table-bordered.table-hover.table-condensed
    %tbody
      %tr.info.text-center
        %td
          %b= "ID"
        %td
          %b= I18n.t('admin_import.name')
        %td
          %b= "swimmer_id"
        %td
          %b= "team_id"
        %td
          %b= "team_affiliation_id"
        %td
          %b= "category_type_id"
      - @badges.each do |badge|
        %tr.text-right
          %td
            = badge.id
          %td.text-left
            = badge.get_full_name
          %td
            = badge.swimmer_id
          %td
            = badge.team_id
          %td
            = badge.team_affiliation_id
          %td
            = badge.category_type_id

- if @di_badges.count > 0
  %h4
    = I18n.t('admin_import.secondary_to_be_committed')
    = " (tot. #{ @di_badges.count })"
  %table.table.table-striped.table-bordered.table-hover.table-condensed
    %tbody
      %tr.info.text-center
        %td
          %b= "ID"
        %td
          %b= I18n.t('admin_import.number')
        %td
          %b= "season_id"
        %td
          %b= "data_import_season_id"
        %td
          %b= "swimmer_id"
        %td
          %b= "data_import_swimmer_id"
        %td
          %b= "team_id"
        %td
          %b= "data_import_team_id"
        %td
          %b= "team_affiliation_id"
        %td
          %b= "category_type_id"
      - @di_badges.each do |badge|
        %tr.text-right
          %td
            = badge.id
          %td
            = badge.number
          %td
            = badge.season_id
          %td
            = badge.data_import_season_id
          %td
            = badge.swimmer_id
          %td
            = badge.data_import_swimmer_id
          %td
            = badge.team_id
          %td
            = badge.data_import_team_id
          %td
            = badge.team_affiliation_id
          %td
            = badge.category_type_id

app/views/data_import/home/_step2_meeting_di_totals.html.haml
.col-xs-5
  %table.table.table-striped.table-bordered.table-hover.table-condensed
    %tbody
      %tr.text-center
        %td{ colspan: 2 }
          %b
            %i= I18n.t('admin_import.already_existing_tot_rows')
      %tr
        %td
          = I18n.t('admin_import.mirs')
        %td.text-right
          = @meeting.meeting_individual_results.distinct.count
      %tr
        %td
          = I18n.t('admin_import.mrrs')
        %td.text-right
          = @meeting.meeting_relay_results.distinct.count
      %tr
        %td
          = I18n.t('admin_import.mtss')
        %td.text-right
          = @meeting.meeting_team_scores.distinct.count

.col-xs-2.text-center
  ="<==(+)=="

.col-xs-5
  %table.table.table-striped.table-bordered.table-hover.table-condensed
    %tbody
      %tr.text-center.success
        %td{ colspan: 2 }
          %b
            %i= I18n.t('admin_import.to_be_committed_tot_rows')
      %tr.success
        %td
          = "Data-import #{ I18n.t('admin_import.mirs') }"
        %td.text-right
          = @di_mirs.distinct.count
      %tr.success
        %td
          = "Data-import #{ I18n.t('admin_import.mrrs') }"
        %td.text-right
          = @di_mrrs.distinct.count
      %tr.success
        %td
          = "Data-import #{ I18n.t('admin_import.mtss') }"
        %td.text-right
          = @di_mtss.distinct.count

app/views/data_import/home/_step2_meeting_programs_show.html.haml
.col-xs-6
  - if @meeting_prgs.count > 0
    %h4
      = I18n.t('admin_import.primary_already_existing')
      = " (tot. #{ @meeting_prgs.count })"
    %table.table.table-striped.table-bordered.table-hover.table-condensed
      %tbody
        %tr.info.text-center
          %td
            %b= "ID"
          %td
            %b= t('calendars.date')
          %td
            %b= t('admin_import.event')
          %td
            %b= t('admin_import.category')
        - @meeting_prgs.each do |meeting_prg|
          %tr
            %td.text-right
              = meeting_prg.id
            %td.text-center
              = meeting_prg.get_scheduled_date
            %td.text-left
              = "(#{ meeting_prg.event_order }) #{ meeting_prg.event_type.i18n_short }"
            %td.text-left
              = meeting_prg.get_category_and_gender_short

.col-xs-6
  - if @di_meeting_prgs.count > 0
    %h4
      = I18n.t('admin_import.secondary_to_be_committed')
      = " (tot. #{ @di_meeting_prgs.count })"
    %table.table.table-striped.table-bordered.table-hover.table-condensed
      %tbody
        %tr.info.text-center
          %td
            %b= "ID"
          %td
            %b= t('calendars.date')
          %td
            %b= t('admin_import.event')
          %td
            %b= t('admin_import.category')
        - @di_meeting_prgs.each do |meeting_prg|
          %tr
            %td.text-right
              = meeting_prg.id
            %td.text-center
              = meeting_prg.get_scheduled_date
            %td.text-left
              = "(#{ meeting_prg.event_order }) #{ meeting_prg.event_type.i18n_short }"
            %td.text-left
              = meeting_prg.get_category_and_gender_short

app/views/data_import/home/step1_1_team_analysis.html.haml
%ul.nav.nav-tabs
  = content_tag( :li, link_to(t('admin_import.step_1'), di_step1_status_path()) )
  = content_tag( :li, link_to(t('admin_import.step_1_1'), '#'), class: 'active' )
  = content_tag( :li, link_to(t('admin_import.step_2'), '#'),   class: 'disabled' )
  = content_tag( :li, link_to(t('admin_import.step_3'), '#'),   class: 'disabled' )

.col-xs-12.goggles-category-gap

%p.text-center.lead
  = I18n.t('admin_import.import_event_results_title')
  \:
  \#{I18n.t('admin_import.team_analysis_results')}
  (#{I18n.t('admin_import.session')}: #{@data_import_session.id})

.row.col-xs-12
  .alert.alert-info
    = I18n.t('admin_import.unconfirmed_results_will_be_added')

.row.col-xs-12
  = form_tag( 'step1_1_team_analysis_commit', multipart: true, class: 'form',     |
        onsubmit: "$('#loadingIndicator').show(); " ) do                          |
    = hidden_field_tag( :data_import_session_id, @data_import_session.id )
    = hidden_field_tag( :force_meeting_creation, @force_missing_meeting_creation ? '1' : '0' )
    = hidden_field_tag( :force_team_or_Team_creation, @force_team_or_Team_creation ? '1' : '0' )
    .row.col-xs-12
      %table.table.table-striped.table-bordered.table-hover.table-condensed#history
        %tbody
          %tr.text-center
            %td{ colspan: 2 }
              = I18n.t('admin_import.searched_team')
            %td{ colspan: 2 }
              = I18n.t('admin_import.team_match_name')
            %td
              = I18n.t('admin_import.add_alias')
            %td
              = I18n.t('admin_import.add_team')
            %td
              = I18n.t('admin_import.add_affiliation')
            %td
              = I18n.t('admin_import.is_ok')
          - @analysis_results.each_with_index do |result_row, idx|
            - do_insert_alias = result_row.can_insert_alias
            - do_insert_team = result_row.can_insert_team
            - do_insert_affiliation = result_row.can_insert_affiliation
            %tr
              %td{ colspan: 2 }
                .dropdown
                  %a.dropdown-toggle{ 'data-toggle' => "dropdown", href: "#" }
                    %b="#{result_row.searched_team_name}"
                  %ul.dropdown-menu
                    - if @data_import_session
                      - data_lines = @data_import_session.source_data.split("\r\n")
                      - data_lines = data_lines.map { |line| ( line =~ Regexp.new(result_row.searched_team_name, 'ui') ) ? line[(line =~ /([a-z]+)/i).to_i .. 76] : nil }.compact.uniq
                      - 2.times { data_lines.delete_at(                           |
                          data_lines.find_index( data_lines.last )                |
                        ) } if data_lines && data_lines.size > 2                  |
                      - data_lines.each do |line|
                        %li
                          %pre.imported_Team= line
              %td{ colspan: 2 }
                .form-group
                  = hidden_field( :alias_ids, result_row.id, value: result_row.chosen_team_id )
                  = text_field_tag( "alias_ids_#{ result_row.id }_name",                              |
                      result_row.chosen_team_id ? Team.find(result_row.chosen_team_id).name : nil,    |
                      {autocomplete: 'off', class: "input-sm form-control typeahead",                 |
                      "data-provide"=>"typeahead", placeholder: I18n.t('combobox_3char_tooltip')} )   |
              %td
                = show_tag( do_insert_alias )
              %td
                = show_tag( do_insert_team )
              %td
                = show_tag( do_insert_affiliation )
              %td
                = check_box_tag( "id_#{result_row.id}", '1', do_insert_team )

    .row.col-xs-12.goggles-category-gap
      .col-xs-6
        = I18n.t('admin_import.on_commit_go_back_to_step1')
      .col-xs-1
        = check_box_tag( "must_go_back" )
      .col-xs-1
        = submit_tag( I18n.t('admin_import.confirm'), data: {disable_with: I18n.t(:please_wait), class: 'btn disabled'}, class: 'btn btn-primary' )
      .col-xs-1
        %span#loadingIndicator{hidden: "true"}
          = image_tag( 'indicator.gif' )
        #divProgress.progress.progress-striped.active{hidden: "true"}

:javascript
  /**
   * AJAX response buffer.
   * Stores the actual array of objects returned by the AJAX request.
   */
  var responseTeamNamesBuffer = [];

  /**
   * Datum tokenizer for the Bloodhound suggestion engine.
   * Returns the datum tokenized into a comparable string.
   */
  function tokenizeTeamNameInStep11( datum ) {
    // Extract just the name part:
    // DEBUG
    //console.log( "tokenizeTeamNameInStep11 datum splitted: ", detokenizeTeamNameInStep11(datum) );
    return Bloodhound.tokenizers.obj.whitespace( detokenizeTeamNameInStep11(datum)[0] );
  }

  /**
   * De-tokenizer for composed results.
   * Splits a specified datum using '|' as internal separator for fields.
   * Returns an array of string tokens, in which, allegedly, the order should be:
   * 1. Team#name
   * 2. remote City ID (as a string number), whenever defined
   * 3. remote Team ID (as a string number)
   */
  function detokenizeTeamNameInStep11( datum ) {
    return datum.split("|");
  }

  /**
   * Remote response adapter for the Bloodhound suggestion engine.
   * It is expected to return a list of tokenized names, ready to be compared/matched.
   */
  function transformTeamNamesResponse( data ) {
    // DEBUG
    //console.log( "transformTeamNamesResponse response: ", data );
    // Clear & rebuild the result list and the list of searchable names:
    responseTeamNamesBuffer = [];

    // Since we're bound to return a list of tokenized & comparable strings,
    // we'll store the additional data to display into the same result row,
    // concatenated with a pipe (which we assume is not used for a name).
    for ( idx = 0; idx < data.length; idx++ ) {
      var composedName = data[idx].name + "|" + data[idx].city_id + "|" + data[idx].id;
      responseTeamNamesBuffer.push( composedName );
    };
    // DEBUG
    //console.log( "responseTeamNamesBuffer:", responseTeamNamesBuffer );
    return responseTeamNamesBuffer;
  }

  /**
   * Bloodhound suggestion engine setup.
   */
  var suggestedTeamNames = new Bloodhound({
    datumTokenizer: tokenizeTeamNameInStep11,
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    // Assuming datum is a JSON-ified instance of the entity, this should return its ID:
    //identify: function( datum ){ return datum.id; },
    remote: {
      url:       "#{ json_search_teams_path( q: 'QUERY') }",
      wildcard:  'QUERY',
      transform: transformTeamNamesResponse
    }
  });

  var typeAheadTeamOptions = {
    name:   'Team-names',
    // This is just for the displaying limit for the menu, not the actual returned results:
    limit:  10,
    asynch: true,
    source: suggestedTeamNames,
    // Displayable value for selections:
    display: function( datum ) {
      // Retrieve the individual tokens to get a displayable value:
      var tokens = detokenizeTeamNameInStep11( datum );
      var namePart   = tokens[0];
      return namePart;
    },
    templates: {
      suggestion: function( datum ) {
        var tokens = detokenizeTeamNameInStep11( datum );
        // DEBUG
        //console.log('tokens: ', tokens);
        return '<div>' + tokens[0] + '&nbsp;<i>(city ID: ' + tokens[1] + ')</i></div>'
      }
    }
  };

  // (Wait for the page to be ready)
  $( function() {
    // Define the typeahead callback handlers:
    $(".typeahead").typeahead(
      { minLength: 3, highlight: true },
      typeAheadTeamOptions
    ).bind('typeahead:select', function( ev, suggestion ) {
        // DEBUG
        //console.log('Selection: ', suggestion);
        // Extract the ID part from the combined string:
        var remote_id = detokenizeTeamNameInStep11( suggestion )[2];
        // DEBUG
        //console.log( "remote_id: ", remote_id );
        // Compose the DOM ID of of the hidden form field to be updated:
        $( '#' + ev.target.id.split("_name")[0] ).val( remote_id );
      }
    );
  });