config/routes.rb
Rails.application.routes.draw do

  mount GogglesCore::Engine => "home/index"

  devise_for :admins

  mount RailsAdmin::Engine => '/dashboard', as: 'rails_admin'

  root to: "data_import/home#step1_status", locale: /en|it/

  scope "/" do
    scope "(:locale)", locale: /it|en/ do
      get   "maintenance/index", as: :maintenance

      get  "maintenance/db_structure"
      post "maintenance/db_reset"
      post "maintenance/run_db_migrations"
      post "maintenance/run_sql_exec"

      get  "maintenance/select_meeting"
      post "maintenance/delete_meeting"
      get  "maintenance/select_teams"

      match "maintenance/run_rake",         to: "maintenance#run_rake",  via: [:get, :post]
      match "maintenance/run_bundle",       to: "maintenance#run_bundle",  via: [:get, :post]
      match "maintenance/run_sudo_command", to: "maintenance#run_sudo_command",  via: [:get, :post]
      match "maintenance/restart_apache",   to: "maintenance#restart_apache",  via: [:get, :post]
      match "maintenance/run_src_upgrade",  to: "maintenance#run_src_upgrade",  via: [:get, :post]
      match "maintenance/upload_db_dump",   to: "maintenance#upload_db_dump",  via: [:get, :post]
      match "maintenance/upload_db_seed",   to: "maintenance#upload_db_seed",  via: [:get, :post]

      get "maintenance/download_db_dump"
      get "maintenance/download_team_dump"
      get "maintenance/download_swimmer_dump"
      get "maintenance/download_user_dump"
      get "maintenance/cleanup_output_dir"

      get  "data_import/home/step1_status",                     as: :di_step1_status
      get  "data_import/home/step1_1_team_analysis",            as: :di_step1_1_team_analysis
      post "data_import/home/step1_1_team_analysis_commit",     as: :di_step1_1_team_analysis_commit
      get  "data_import/home/step1_1_swimmer_analysis",         as: :di_step1_1_swimmer_analysis
      post "data_import/home/step1_1_swimmer_analysis_commit",  as: :di_step1_1_swimmer_analysis_commit
      post "data_import/home/step2_checkout",                   as: :di_step2_checkout
      get  "data_import/home/step2_checkout",                   as: :di_step2_checkout_get
      post "data_import/home/step3_commit",                     as: :di_step3_commit
      post "data_import/home/kill_import_session",              as: :di_kill_import_session

      get  "data_import/home/result/:id",   to: "data_import/home#result", as: "di_result"
    end
  end

  get 'json_search/swimmers', format: "json"
  get 'json_search/teams',    format: "json"
  get 'json_search/meetings', format: "json"
  get 'json_search/pools',    format: "json"
end

app/controllers/admin/v2/maintenance_controller.rb
# encoding: utf-8
require 'fileutils'                                 # Used to process filenames
require 'open3'                                     # Used to capture & send STDIN/STDOUT
require 'common/format'

require_relative '../../../data_import/v2/services/team_merger'


=begin

= MaintenanceController (previously: AdminIndexController)

  - version:  4.00.815
  - author:   Steve A.

=end
class Admin::V2::MaintenanceController < ApplicationController

  layout 'admin_v2_maintenance'

  # Require authorization before invoking any of this controller's actions:
  before_action :authenticate_admin!
  # ---------------------------------------------------------------------------


  # Allows the display of the parameter :console_output, when defined and not empty
  #
  # === Params:
  # - console_output: when not nil can be a string text to be displayed,
  #   containing the captured console output from the previous command execution
  #   (that has then redirected the server here).
  #
  def index
    @console_output = params[:console_output]
    output_folder = File.join( File.join(Rails.root, 'public'), 'output' )
    @existing_output_files = Dir.glob( File.join(output_folder, '*'), File::FNM_PATHNAME ).sort
  end
  # ---------------------------------------------------------------------------


  # Allows to upload and execute a compressed SQL dump of the whole
  # database.
  #
  # === Params:
  # - :datafile => the uploaded file (mandatory on POST)
  # - console_output: when not nil can be a string text to be displayed,
  #   containing the captured console output from the previous command execution
  #   (that has then redirected the server here).
  #
  def upload_db_dump
# DEBUG
#    logger.debug "\r\n\r\n!! ------ upload_db_dump() -----"
#    logger.debug "PARAMS: #{params.inspect}"
    @console_output = ''
    @filename_to_be_run = nil
    if request.post?
      if params[:datafile]
        tmp_file = params[:datafile].tempfile         # (This is an ActionDispatch::Http::UploadedFile object)
        filename = File.join( "public/uploads", params[:datafile].original_filename )
        FileUtils.cp tmp_file.path, filename
        ext = File.extname( filename )
        zip_pipe = nil

        case ext
        when '.bz2'
          zip_pipe = 'bzip2 -d '
        when '.tgz'
          zip_pipe = 'gzip -d '
        when '.zip'
          zip_pipe = 'unzip '
        when '.sql'
          zip_pipe = nil
        else
          flash[:info] = I18n.t(:unsupported_file_format, { scope: [:admin_index] })
          redirect_to( admin_v2_maintenance_path() ) and return
        end

        if zip_pipe
          @filename_to_be_run = filename.split(ext)[0]
        else
          @filename_to_be_run = filename
        end
        rails_config  = Rails.configuration
        db_name       = rails_config.database_configuration[Rails.env]['database']
        db_user       = rails_config.database_configuration[Rails.env]['username']
        db_pwd        = rails_config.database_configuration[Rails.env]['password']
                                                    # Build up the mysql execution command:
        mysql_cmd     = "mysql --user=#{db_user} --password=\"#{db_pwd}\""
        mysql_cmd << " --database=#{db_name}" unless ( params[:is_a_full_dump] == '1' )
        mysql_cmd << " --execute=\"\\. #{@filename_to_be_run}\""
                                                    # Log what the admin is been doing:
        logger.info( "\r\n---- upload_db_dump( #{@filename_to_be_run} ) ----" )
        logger.info( "#{current_admin.name} is executing \"#{mysql_cmd}\"...\r\n" )

        @console_output = "Executing \"#{mysql_cmd}\"...\r\n"
        @console_output << `#{zip_pipe} #{filename}` if zip_pipe
        @console_output << `#{mysql_cmd}`
        @console_output.gsub!(/\s--password=".*"\s/, ' --password=[***] ')

        @console_output << "Deleting '#{@filename_to_be_run}'...\r\n"
        logger.info( "Deleting '#{@filename_to_be_run}'...\r\n" )
        FileUtils.rm( @filename_to_be_run ) if File.exists?( @filename_to_be_run )
      else
        flash[:info] = I18n.t(:nothing_to_do_upload_something, { scope: [:admin_import] })
        redirect_to( admin_v2_maintenance_path() ) and return
      end
    end
  end


  # Allows to upload and execute a compressed SQL file containing what is
  # supposed to be new, additional, 'seed' data. The file can then either be
  # stored into our standard seed directory (db/seed) or deleted upon
  # user request.
  #
  # === Params:
  # - :datafile => the uploaded file (mandatory on POST)
  # - console_output: when not nil can be a string text to be displayed,
  #   containing the captured console output from the previous command execution
  #   (that has then redirected the server here).
  #
  def upload_db_seed
# DEBUG
#    logger.debug "\r\n\r\n!! ------ upload_db_seed() -----"
#    logger.debug "PARAMS: #{params.inspect}"
    @console_output = ''
    @filename_to_be_run = nil
    if request.post?
      if params[:datafile]
        tmp_file = params[:datafile].tempfile         # (This is an ActionDispatch::Http::UploadedFile object)
        filename = File.join( "public/uploads", params[:datafile].original_filename )
        FileUtils.cp tmp_file.path, filename
        ext = File.extname( filename )
        zip_pipe = nil

        case ext
        when '.bz2'
          zip_pipe = 'bzip2 -d '
        when '.tgz'
          zip_pipe = 'gzip -d '
        when '.zip'
          zip_pipe = 'unzip '
        when '.sql'
          zip_pipe = nil
        else
          flash[:info] = I18n.t(:unsupported_file_format, { scope: [:admin_index] })
          redirect_to( admin_v2_maintenance_path() ) and return
        end

        if zip_pipe
          @filename_to_be_run = filename.split(ext)[0]
        else
          @filename_to_be_run = filename
        end
        rails_config  = Rails.configuration
        db_name       = rails_config.database_configuration[Rails.env]['database']
        db_user       = rails_config.database_configuration[Rails.env]['username']
        db_pwd        = rails_config.database_configuration[Rails.env]['password']
                                                    # Build up the mysql execution command:
        mysql_cmd     = "mysql --user=#{db_user} --password=\"#{db_pwd}\" --database=#{db_name} --execute=\"\\. #{@filename_to_be_run}\""
                                                    # Log what the admin is been doing:
        logger.info( "\r\n---- upload_db_dump( #{@filename_to_be_run} ) ----" )
        logger.info( "#{current_admin.name} is executing \"#{mysql_cmd}\"...\r\n" )

        @console_output = "Executing \"#{mysql_cmd}\"...\r\n"
        @console_output << `#{zip_pipe} #{filename}` if zip_pipe
        @console_output << `#{mysql_cmd}`
        @console_output.gsub!(/\s--password=".*"\s/, ' --password=[***] ')

        if ( params[:store_to_seed_dir] == '1' )
          dest_filename = File.join( "db/seed", File.basename(@filename_to_be_run) )
          @console_output << "Storing file '#{dest_filename}'...\r\n"
          logger.info( "Storing file '#{dest_filename}'...\r\n" )
          FileUtils.mv( @filename_to_be_run, dest_filename ) if File.exists?( @filename_to_be_run )
        else
          @console_output << "Deleting '#{@filename_to_be_run}'...\r\n"
          logger.info( "Deleting '#{@filename_to_be_run}'...\r\n" )
          FileUtils.rm( @filename_to_be_run ) if File.exists?( @filename_to_be_run )
        end
      else
        flash[:info] = I18n.t(:nothing_to_do_upload_something, { scope: [:admin_import] })
        redirect_to( admin_v2_maintenance_path() ) and return
      end
    end
  end
  # ---------------------------------------------------------------------------


  # Executes a full mysqldump command.
  #
  def download_db_dump
    execute_mysqldump_with_send_file()
  end

  def download_team_dump
    execute_mysqldump_with_send_file( ['teams', 'team_affiliations', 'data_import_team_aliases', 'cities'] )
  end

  def download_swimmer_dump
    execute_mysqldump_with_send_file( ['swimmers', 'badges'] )
  end

  def download_user_dump
    execute_mysqldump_with_send_file( ['users', 'admins'] )
  end
  # ---------------------------------------------------------------------------

  def cleanup_output_dir
    output_folder = File.join( File.join(Rails.root, 'public'), 'output' )
    FileUtils.rm( Dir.glob(File.join(output_folder,'*')) )
    redirect_to admin_v2_maintenance_path()
  end
  # ---------------------------------------------------------------------------
  # ---------------------------------------------------------------------------


  # Displays :console_output as index does, but shows also several buttons
  # to execute pre-build rake tasks.
  #
  # === Params:
  # - console_output: when not nil can be a string text to be displayed,
  #   containing the captured console output from the previous command execution
  #   (that has then redirected the server here).
  #
  def db_structure
# DEBUG
#    logger.debug "\r\n\r\n!! ------ db_structure() -----"
#    logger.debug "PARAMS: #{params.inspect}"
    @console_output = params[:console_output]
  end


  def db_reset
    @console_output = ''
    if request.post?
      logger.info( "\r\n\r\n!! ------ db_reset() -----" )
      logger.info( "#{current_admin.name} is executing a DB:REBUILD_FROM_DUMP...\r\n" )
      output = "Executing DB:REBUILD_FROM_DUMP...\r\n"
      is_ok = execute_cmd( 'bundle exec rake', 'db:rebuild_from_dump' )
      output << "\r\nExecution of 'rake db:rebuild_from_dump' #{ is_ok ? 'OK!' : 'FAILED!'}\r\n"
      @console_output = output                      # Cannot use full console output because it's too big!
    end
    redirect_to db_structure_path( console_output: @console_output )
  end


  def run_db_migrations
    @console_output = ''
    if request.post?
      logger.info( "\r\n---- run_db_migrations() ----" )

app/views/maintenance/_main_menu.html.haml
.navbar.navbar-fixed-top
  .navbar-inner#goggles-inner-navbar
    %a.goggles-brand(href="#{maintenance_path()}")
      %span &nbsp;
      = GogglesCore::AppConstants::WEB_APP_NAME
      %small.text-error
        %strong= t('admin_index.title')
    = render_navigation( context: 'maintenance', expand_all: true, renderer: :bootstrap )

.goggles-breadcrumb
  = render_navigation( context: 'maintenance', renderer: :breadcrumbs, prefix: "#{I18n.t(:you_are_here)}&nbsp;", join_with: " &gt; " )

app/views/maintenance/_search_meeting_grid.html.erb
<%= define_grid(@meetings_grid, hide_submit_button: true, hide_reset_button: true) do |g|
    g.blank_slate do
        content_tag( :div, t(:no_data_found), class: 'well' )
    end

    g.column( name: 'ID', attribute: 'id', filter: false ) do |meeting|
        form_tag( :delete_meeting, class: 'form-horizontal',
                  :onsubmit => "$('#loadIndicator').show(); ") do
            submit_tag( meeting.id,
                        data: {
                            confirm: I18n.t('netzke.basepack.grid_panel.are_you_sure'),
                            :disable_with => I18n.t(:please_wait),
                            class: 'btn disabled'
                        }, class: 'btn btn-primary'
            )
        end
    end

    g.column(
        name: I18n.t(:description),
        attribute: 'description'
    ) do |meeting|
        meeting.description
    end

    g.column(
        name: I18n.t(:season_type, { scope: [:activerecord, :models] }),
        model: Season,
        attribute: 'season_type_id',
        custom_filter: SeasonType.to_dropdown,
        detach_with_id: :flt_season_type_id,
    ) do |meeting|
        meeting.season.get_season_type if meeting.season
    end

    g.column(
        name: I18n.t(:season, { scope: [:activerecord, :models] }),
        attribute: 'season_id',
        custom_filter: Season.to_dropdown,
        detach_with_id: :flt_season_id
    ) do |meeting|
        meeting.season.get_full_name if meeting.season
    end

    g.column(
        name: I18n.t('meeting.total_results_short')
    ) do |meeting|
        ( meeting.meeting_individual_results.count + meeting.meeting_relay_results.count )
    end

    g.column(
        name: I18n.t(:any_date),
        attribute: 'header_date',
        detach_with_id: :flt_entry_header_date
    ) do |meeting|
        meeting.header_date
    end

    g.column(
        name: I18n.t(:are_results_acquired, { scope: [:activerecord, :attributes, :meeting] }),
        attribute: 'are_results_acquired'
    ) do |meeting|
        meeting.are_results_acquired? ? 'Ok' : '-'
    end
end -%>

app/views/maintenance/db_structure.html.haml
%p.text-center.lead= I18n.t('admin_index.db_structure')

.row.span4
  = form_tag( :db_reset, class: 'form-horizontal', :onsubmit => "$('#loadIndicator1').show(); ") do
    = submit_tag( I18n.t('admin_index.db_reset'), confirm: I18n.t('netzke.basepack.grid_panel.are_you_sure'), :data => {:disable_with => I18n.t(:please_wait), class: 'btn disabled'}, class: 'btn btn-primary' )
    %span(id='loadIndicator1' hidden='true')
      = image_tag( 'indicator.gif' )
.row.span2
  = form_tag( :run_db_migrations, class: 'form-horizontal', :onsubmit => "$('#loadIndicator2').show(); ") do
    = submit_tag( I18n.t('admin_index.run_db_migrations'), :data => {:disable_with => I18n.t(:please_wait), class: 'btn disabled'}, class: 'btn btn-primary' )
    %span(id='loadIndicator2' hidden='true')
      = image_tag( 'indicator.gif' )
.row.span4
  = form_tag( :run_sql_exec, class: 'form-horizontal', :onsubmit => "$('#loadIndicator3').show(); ") do
    = submit_tag( I18n.t('admin_index.run_sql_exec'), confirm: I18n.t('netzke.basepack.grid_panel.are_you_sure'), :data => {:disable_with => I18n.t(:please_wait), class: 'btn disabled'}, class: 'btn btn-primary' )
    %span(id='loadIndicator3' hidden='true')
      = image_tag( 'indicator.gif' )

.row.span11
  - if (@console_output && @console_output.size > 0)
    %hr
    %pre.prettyprint.linenums= @console_output

app/views/maintenance/index.html.haml
%p.text-center.lead= I18n.t('admin_index.title')

.row.span11
  - if @existing_output_files.instance_of?(Array) && (@existing_output_files.size > 0)
    .row
      %b= I18n.t('admin_index.existing_output_files')
    - @existing_output_files.each do |filename|
      .row
        %i.linenums= filename

.row.span11
  - if (@console_output && @console_output.size > 0)
    %hr
    %pre.prettyprint.linenums= @console_output

app/views/maintenance/restart_apache.html.haml
.text-center
  .lead= I18n.t('admin_index.restart_apache')
  %i= I18n.t('admin_index.restart_apache_info')

.row.span11

.row.span11
  = form_tag( :restart_apache, class: 'form-horizontal', :onsubmit => "$('#loadingIndicator').show(); ") do
    .control-group
      = label_tag( :password, t(:password), :for => :password, class: 'control-label' )
      .controls
        = password_field_tag( :password, nil, class: 'input-large' )

    .control-group
      .controls
        = submit_tag( I18n.t('admin_index.go'), :data => {:disable_with => I18n.t(:please_wait), class: 'btn disabled'}, class: 'btn btn-primary' )
        %span(id='loadingIndicator' hidden='true')
          = image_tag( 'indicator.gif' )

.row.span11
  - if (@console_output && @console_output.size > 0)
    %hr
    %pre.prettyprint.linenums= @console_output

app/views/maintenance/run_bundle.html.haml
.text-center
  .lead= I18n.t('admin_index.execute_bundle_command')
  %i= I18n.t('admin_index.execute_bundle_command_info')

.row.span11

.row.span11
  = form_tag( :run_bundle, class: 'form-horizontal', :onsubmit => "$('#loadingIndicator').show(); ") do
    .control-group
      = label_tag( :bundle_cmd, t('admin_index.bundle_cmd'), :for => :bundle_cmd, class: 'control-label' )
      .controls
        = text_field_tag( :bundle_cmd, nil, class: 'input-xxlarge' )

    .control-group
      .controls
        = submit_tag( I18n.t('admin_index.go'), :data => {:disable_with => I18n.t(:please_wait), class: 'btn disabled'}, class: 'btn btn-primary' )
        %span(id='loadingIndicator' hidden='true')
          = image_tag( 'indicator.gif' )

.row.span11
  - if (@console_output && @console_output.size > 0)
    %hr
    %pre.prettyprint.linenums= @console_output

app/views/maintenance/run_rake.html.haml
.text-center
  .lead= I18n.t('admin_index.execute_rake_command')
  %i= I18n.t('admin_index.execute_rake_command_info')

.row.span11

.row.span11
  = form_tag( :run_rake, class: 'form-horizontal', :onsubmit => "$('#loadingIndicator').show(); ") do
    .control-group
      = label_tag( :rake_cmd, t('admin_index.rake_cmd'), :for => :rake_cmd, class: 'control-label' )
      .controls
        = text_field_tag( :rake_cmd, nil, class: 'input-xxlarge' )

    .control-group
      .controls
        = submit_tag( I18n.t('admin_index.go'), :data => {:disable_with => I18n.t(:please_wait), class: 'btn disabled'}, class: 'btn btn-primary' )
        %span(id='loadingIndicator' hidden='true')
          = image_tag( 'indicator.gif' )

.row.span11
  - if (@console_output && @console_output.size > 0)
    %hr
    %pre.prettyprint.linenums= @console_output

app/views/maintenance/run_src_upgrade.html.haml
.text-center
  .lead= I18n.t('admin_index.execute_source_upgrade')
  %i= I18n.t('admin_index.execute_source_upgrade_info')

.row.span11


.row.span11
  = form_tag( :run_src_upgrade, class: 'form-horizontal', :onsubmit => "$('#loadingIndicator').show(); ") do
    .control-group
      = label_tag( :backup_folder, t('admin_index.backup_dir'), :for => :backup_folder, class: 'control-label' )
      .controls
        = text_field_tag( :backup_folder, @default_backup_folder, class: 'input-xxlarge' )
    .control-group
      = label_tag( :password, t(:password), :for => :password, class: 'control-label' )
      .controls
        = password_field_tag( :password, nil, class: 'input-large' )

    .control-group
      .controls
        = submit_tag( I18n.t('admin_index.git_pull'), confirm: I18n.t('admin_import.are_you_sure'), :data => {:disable_with => I18n.t(:please_wait), class: 'btn disabled'}, class: 'btn btn-primary' )
        %span(id='loadingIndicator' hidden='true')
          = image_tag( 'indicator.gif' )

.row.span11
  - if (@console_output && @console_output.size > 0)
    %hr
    %pre.prettyprint.linenums= @console_output

app/views/maintenance/run_sudo_command.html.haml
.text-center
  .lead= I18n.t('admin_index.execute_sudo_command')
  %i= I18n.t('admin_index.execute_sudo_command_info')

.row.span11

.row.span11
  = form_tag( :run_sudo_command, class: 'form-horizontal', :onsubmit => "$('#loadingIndicator').show(); ") do
    .control-group
      = label_tag( :sudo_cmd, t('admin_index.sudo_cmd'), :for => :sudo_cmd, class: 'control-label' )
      .controls
        = text_field_tag( :sudo_cmd, nil, class: 'input-xxlarge' )
    .control-group
      = label_tag( :password, t(:password), :for => :password, class: 'control-label' )
      .controls
        = password_field_tag( :password, nil, class: 'input-large' )

    .control-group
      .controls
        = submit_tag( I18n.t('admin_index.go'), :data => {:disable_with => I18n.t(:please_wait), class: 'btn disabled'}, class: 'btn btn-primary' )
        %span(id='loadingIndicator' hidden='true')
          = image_tag( 'indicator.gif' )

.row.span11
  - if (@console_output && @console_output.size > 0)
    %hr
    %pre.prettyprint.linenums= @console_output

app/views/maintenance/select_meeting.html.haml
= render partial: 'search_meeting_grid'

.accordion#accordionFlt
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{'data-toggle' => 'collapse', 'data-parent' => '#accordionFlt', :href => '#collapseFlt'}
        %h3#headerFlt{'data-toggle' => 'tooltip', 'title' => I18n.t(:search_tooltip)}= @title
        %span( id='loadIndicator' hidden='true' )
          = image_tag( 'indicator.gif' )
        %script
          $('#headerFlt').tooltip(placement:'bottom')

    .accordion-body.collapse.in#collapseFlt
      .accordion-inner
        .row-fluid
          .span2
            = I18n.t(:season_type, { scope: [:activerecord, :models] })
          .span10
            = grid_filter @meetings_grid, :flt_season_type_id
        .row-fluid
          .span2
            = I18n.t(:season, { scope: [:activerecord, :models] })
          .span10
            = grid_filter @meetings_grid, :flt_season_id
        .row-fluid
          .span2
            = I18n.t(:any_date)
          .span10
            = grid_filter @meetings_grid, :flt_entry_header_date
        .row-fluid
          .span12
            .external-buttons
              %button.btn.btn-primary.wg-external-submit-button{'data-grid-name' => 'grid'}
                = I18n.t(:submit)
              %button.btn.wg-external-reset-button{'data-grid-name' => 'grid'}
                = I18n.t(:reset)

.row-fluid
  .span12
    = render_grid( @meetings_grid )

app/views/maintenance/select_teams.html.haml
.text-center
  .lead= I18n.t('admin_index.merge_teams')
  %i= I18n.t('admin_index.merge_teams_info')

.row-fluid
  .span12
%script
  function validateSubmit() { $('#submitBtn').attr('disabled', ($('#merge_teams_src_id')[0].value == $('#merge_teams_dest_id')[0].value)); }
  function ajaxCount(label_id, team_id) { $(label_id).load( "#{count_details_team_path(:id=>-1)}".replace('-1',team_id) ); }

= form_for :merge_teams, html: {onsubmit: "$('#loadingIndicator').show();"} do |f|
  .row-fluid
    .span3= I18n.t('admin_index.select_source_team')
    .span4= f.select( :src_id, Team.to_dropdown(nil, :id, :get_full_name_with_id), {prompt: I18n.t(:please_select)}, {class: 'input-xlarge', onchange: "validateSubmit(); ajaxCount('#labelSrc', $('#merge_teams_src_id')[0].value);"} )
    .span4
      %i(id='labelSrc')
  .row-fluid
    .span3= I18n.t('admin_index.select_dest_team')
    .span4= f.select( :dest_id, Team.to_dropdown(nil, :id, :get_full_name_with_id), {prompt: I18n.t(:please_select)}, {class: 'input-xlarge', onchange: "validateSubmit(); ajaxCount('#labelDest', $('#merge_teams_dest_id')[0].value);"} )
    .span4
      %i(id='labelDest')
  .row-fluid
    .offset3.span2
      %p= f.submit( I18n.t('admin_index.merge_teams'), id: 'submitBtn', :data => {disable_with: I18n.t(:please_wait), class: 'btn disabled'}, class: 'btn btn-primary' )
    .span2
      %span(id='loadingIndicator' hidden='true')
        = image_tag( 'indicator.gif' )

.row-fluid
  .span12
.row-fluid
  .span12
    - if (@console_output && @console_output.size > 0)
      %hr
      %pre.prettyprint.linenums= @console_output

app/views/maintenance/upload_db_dump.html.haml
.text-center
  .lead= I18n.t('admin_index.upload_db_dump')
  %i= I18n.t('admin_index.upload_db_dump_info')

.row.span11

.row.span11
  = form_tag( :upload_db_dump, :multipart => true, class: 'form-horizontal', :onsubmit => "$('#loadingIndicator').show(); ") do
    .control-group
      = label_tag( :datafile, t('admin_index.upload_db_dump'), :for => :datafile, class: 'control-label' )
      .controls
        = file_field_tag( :datafile )
    .control-group
      = label_tag( :is_a_full_dump, t('admin_index.is_a_full_dump'), :for => :is_a_full_dump, class: 'control-label' )
      .controls
        = check_box_tag( :is_a_full_dump, '1', true )

    .control-group
      .controls
        = submit_tag( I18n.t('admin_index.go'), :data => {:disable_with => I18n.t(:please_wait), class: 'btn disabled'}, class: 'btn btn-primary' )
        %span(id='loadingIndicator' hidden='true')
          = image_tag( 'indicator.gif' )

.row.span11
  - if (@filename_to_be_run && @filename_to_be_run.size > 0)
    %hr
    %pre.prettyprint= @filename_to_be_run

.row.span11
  - if (@console_output && @console_output.size > 0)
    %hr
    %pre.prettyprint= @console_output

app/views/maintenance/upload_db_seed.html.haml
.text-center
  .lead= I18n.t('admin_index.upload_db_seed')
  %i= I18n.t('admin_index.upload_db_seed_info')

.row.span11

.row.span11
  = form_tag( :upload_db_seed, :multipart => true, class: 'form-horizontal', :onsubmit => "$('#loadingIndicator').show(); ") do
    .control-group
      = label_tag( :datafile, t('admin_index.upload_db_seed'), :for => :datafile, class: 'control-label' )
      .controls
        = file_field_tag( :datafile )
    .control-group
      = label_tag( :store_to_seed_dir, t('admin_index.store_to_seed_dir'), :for => :store_to_seed_dir, class: 'control-label' )
      .controls
        = check_box_tag( :store_to_seed_dir, '1', true )

    .control-group
      .controls
        = submit_tag( I18n.t('admin_index.go'), :data => {:disable_with => I18n.t(:please_wait), class: 'btn disabled'}, class: 'btn btn-primary' )
        %span(id='loadingIndicator' hidden='true')
          = image_tag( 'indicator.gif' )

.row.span11
  - if (@filename_to_be_run && @filename_to_be_run.size > 0)
    %hr
    %pre.prettyprint= @filename_to_be_run

.row.span11
  - if (@console_output && @console_output.size > 0)
    %hr
    %pre.prettyprint= @console_output